package Kaori.wiki.entidades;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

@Entity
@Table(name = "Capitulos")
public class Capitulo {
	@Id
	private String idCapitulo;
	//BTW En este caso queremos que el AUTOGENERATED Serie*temporada*num ?? Sí, creo(por seguridad creo que no es recomendable hacer eso)
	// tipo; idCap = EVA0105 (Evangelion s1 e5) 							no tendremos problemas de seguridad porque nadie va a hacker un grupo de chicos de una u
	// in wich case -> idSerie: String										pero por buenas practicas jsjs
	private int numCap;
	private String tituloCap;
	
	@ManyToOne
	@JoinColumn(name = "idTemporada")
	private Temporada temporada;

	public String getIdCapitulo() {
		return idCapitulo;
	}

	public void setIdCapitulo(String idCapitulo) {
		this.idCapitulo = idCapitulo;
	}

	public int getNumCap() {
		return numCap;
	}

	public void setNumCap(int numCap) {
		this.numCap = numCap;
	}

	public String getTituloCap() {
		return tituloCap;
	}

	public void setTituloCap(String tituloCap) {
		this.tituloCap = tituloCap;
	}

	public Temporada getTemporada() {
		return temporada;
	}

	public void setTemporada(Temporada temporada) {
		this.temporada = temporada;
	}
	
}
